local_kaggle_dataset_dir: /media/kyotaro/ubuntu_volume_1/Dataset/kaggle/czii-cryo-et-object-identification
experiment_name: 3dunet_pretrain_submit

#train
seed: 1234
patch_size: 96
batch_size: 16
lr: 1e-3
epochs: 999
val_interval: 1

#test
model_folder: 20250130_103700_3dunet_16_1e-3_999_96x96x96

based_on_fold2: False
# certainty_threshold: 0.5
# certainty_threshold: [0.5, 0.55, 0.55, 0.95, 0.95, 0.95, 0.7]
certainty_threshold: [0.5, 0.05, 0.95, 0.9, 0.95, 0.95, 0.95]

blob_threshold: 150
tta: False
tta_k_rotate: 3

overlap: [1,2,2]
